### ISSUE TITLE
From Radoslaw

### ISSUE THREAD

**Issue by ChrisPrusik** [G1ANT-Robot/G1ANT.Manual#3]
- w GUI mamy komendę xlsx a w dokumentacji xls - rozumiem, że to literówka, albo dokumentacja do poprzedniej wersji.
- w tym samym dziale jest komenda 'xls.setsheet' a przykłady do niej to xml.setsheet :wink:
- bardzo chciałem ukończyć 5 lekcje z waszego tutoriala niestety GitHub zjadł plik excelowski do cwiczenia.

**Comment by WiktoriaPrusik** [comment]
dziękuję za informacje, zostało poprawione 😊
